package controller;

public enum Commands {
    FORWARD, BACKWARD, LEFT, RIGHT, LEFTCLICK, RIGHTCLICK, SPEED_0025, SPEED_01, SPEED_1, REMOVE, ADD, JUMP, START_DEBUG, END_DEBUG,
    PLACE_LIGHT, REMOVE_LIGHT, CREATE_LEVEL, ID0, ID1, ID2, ID3
}

